# Generated by Django 3.2.12 on 2024-02-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=200)),
                ('admin_email', models.EmailField(max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_mobile_number', models.CharField(max_length=20)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_number', models.CharField(max_length=200)),
                ('registration_doc', models.FileField(upload_to='files/')),
                ('pan_number', models.CharField(max_length=200)),
                ('pan_number_doc', models.FileField(upload_to='files/')),
                ('gst_number', models.CharField(max_length=200)),
                ('gst_number_doc', models.FileField(upload_to='files/')),
                ('interest', models.CharField(max_length=100)),
                ('society_reg_address', models.TextField()),
                ('society_city', models.CharField(max_length=100)),
                ('socity_state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('society_corr_reg_address', models.TextField(blank=True, null=True)),
                ('society_corr_city', models.CharField(blank=True, max_length=100, null=True)),
                ('socity_corr_state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_corr_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyRegistrationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_cert', models.FileField(upload_to='files/')),
                ('occupancy_cert', models.FileField(upload_to='files/')),
                ('deed_of_conveyance', models.FileField(upload_to='files/')),
                ('society_by_law', models.FileField(upload_to='files/')),
                ('soc_other_document', models.FileField(blank=True, null=True, upload_to='files/')),
                ('soc_other_document_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('society_creation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.societycreation')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyOtherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_document', models.FileField(upload_to='files/')),
                ('other_document_specification', models.CharField(max_length=100)),
                ('society_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.societycreation')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyBankCreationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_code', models.CharField(max_length=100)),
                ('beneficiary_acc_number', models.CharField(max_length=100)),
                ('beneficiary_bank', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('society_creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.societycreation')),
            ],
        ),
    ]
