# Generated by Django 3.2.12 on 2024-02-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocietyBankCreationNew',
            new_name='SocietyBank',
        ),
    ]
