# Generated by Django 4.0 on 2024-02-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0002_rename_societybankcreationnew_societybank'),
    ]

    operations = [
        migrations.CreateModel(
            name='WingFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing_name', models.CharField(max_length=50)),
                ('flat_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WingFlatUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing_flat_unique', models.CharField(max_length=300)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflat')),
            ],
        ),
    ]
