# Generated by Django 3.2.12 on 2024-02-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0003_wingflat_wingflatunique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('ownership_percent', models.IntegerField()),
                ('member_position', models.CharField(max_length=200)),
                ('member_dob', models.DateField()),
                ('member_pan_no', models.CharField(max_length=200)),
                ('member_aadhar_no', models.CharField(max_length=200)),
                ('member_address', models.CharField(max_length=200)),
                ('member_state', models.CharField(max_length=200)),
                ('member_pin_code', models.CharField(max_length=200)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_contact', models.CharField(max_length=200)),
                ('member_emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('member_occupation', models.CharField(max_length=200)),
                ('member_is_primary', models.BooleanField(blank=True, default=False, null=True)),
                ('date_of_admission', models.DateField()),
                ('age_at_date_of_admission', models.IntegerField()),
                ('sales_agreement', models.FileField(upload_to='files/')),
                ('other_attachment', models.FileField(blank=True, null=True, upload_to='files/')),
                ('date_of_entrance_fees', models.DateField()),
                ('date_of_cessation', models.DateField(blank=True, null=True)),
                ('reason_for_cessation', models.CharField(blank=True, max_length=200, null=True)),
                ('flat_status', models.CharField(max_length=200)),
                ('same_flat_member_identification', models.CharField(max_length=100)),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique', verbose_name='Flat No.')),
            ],
        ),
        migrations.CreateModel(
            name='Nominees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=300)),
                ('date_of_nomination', models.DateField()),
                ('relation_with_nominee', models.CharField(max_length=300)),
                ('nominee_sharein_percent', models.IntegerField()),
                ('nominee_dob', models.DateField()),
                ('nominee_aadhar_no', models.CharField(max_length=300)),
                ('nominee_pan_no', models.CharField(max_length=300)),
                ('nominee_email', models.EmailField(max_length=254)),
                ('nominee_address', models.CharField(max_length=300)),
                ('nominee_state', models.CharField(max_length=300)),
                ('nominee_pin_code', models.CharField(max_length=300)),
                ('nominee_contact', models.CharField(max_length=300)),
                ('nominee_emergency_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members')),
            ],
        ),
    ]
