# Generated by Django 3.2.12 on 2024-02-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0005_auto_20240225_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(max_length=300)),
                ('shares_date', models.DateField()),
                ('application_number', models.CharField(max_length=300)),
                ('shares_certificate', models.CharField(max_length=300)),
                ('allotment_number', models.CharField(max_length=300)),
                ('shares_from', models.CharField(max_length=300)),
                ('shares_to', models.CharField(max_length=300)),
                ('shares_transfer_date', models.DateField()),
                ('total_amount_received', models.IntegerField()),
                ('total_amount_date', models.DateField()),
                ('transfer_from_folio_no', models.CharField(max_length=300)),
                ('transfer_to_folio_no', models.CharField(max_length=300)),
                ('date_of_cessation', models.DateField(blank=True, null=True)),
                ('unique_member_shares', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique')),
            ],
        ),
    ]
