# Generated by Django 3.2.12 on 2024-02-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0006_flatshares'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberVehicleRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lot', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('vehicle_number', models.CharField(max_length=200)),
                ('vehicle_brand', models.CharField(max_length=200)),
                ('rc_copy', models.FileField(upload_to='files/')),
                ('sticker_number', models.CharField(max_length=200)),
                ('chargable', models.CharField(default='', max_length=200)),
                ('date_of_cessation', models.DateField(blank=True, null=True)),
                ('unique_member_shares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique')),
            ],
        ),
        migrations.CreateModel(
            name='HomeLoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_loan_name', models.CharField(max_length=300)),
                ('bank_loan_object', models.CharField(max_length=300)),
                ('bank_loan_date', models.DateField()),
                ('bank_loan_value', models.CharField(max_length=300)),
                ('bank_loan_acc_no', models.CharField(max_length=300)),
                ('bank_loan_installment', models.CharField(max_length=300)),
                ('bank_loan_status', models.BooleanField(default=False)),
                ('bank_loan_remark', models.CharField(max_length=300)),
                ('bank_noc_file', models.FileField(upload_to='files/')),
                ('date_of_cessation', models.DateField(blank=True, null=True)),
                ('unique_member_shares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique')),
            ],
        ),
        migrations.CreateModel(
            name='GSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(max_length=300)),
                ('gst_state', models.CharField(max_length=300)),
                ('gst_billing_name', models.CharField(max_length=300)),
                ('gst_billing_address', models.CharField(max_length=300)),
                ('gst_contact_no', models.CharField(max_length=300)),
                ('date_of_cessation', models.DateField(blank=True, null=True)),
                ('unique_member_shares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique')),
            ],
        ),
    ]
