# Generated by Django 3.2.12 on 2024-02-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0007_gstdetails_homeloandetails_membervehicleregister'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GSTDetails',
            new_name='FlatGST',
        ),
        migrations.RenameModel(
            old_name='HomeLoanDetails',
            new_name='FlatHomeLoan',
        ),
        migrations.RenameModel(
            old_name='MemberVehicleRegister',
            new_name='FlatMemberVehicle',
        ),
    ]
