# Generated by Django 3.2.12 on 2024-02-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0008_auto_20240225_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flathomeloan',
            name='bank_noc_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
