# Generated by Django 3.2.12 on 2024-02-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0009_alter_flathomeloan_bank_noc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmembervehicle',
            name='sticker_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
