# Generated by Django 3.2.12 on 2024-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0010_alter_flatmembervehicle_sticker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='flat_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
