# Generated by Django 3.2.12 on 2024-02-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0011_alter_members_flat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominees',
            name='member_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='SocietyApi.members'),
        ),
    ]
