# Generated by Django 3.2.12 on 2024-02-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0012_alter_nominees_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_help_name', models.CharField(error_messages={'blank': 'Name is required!'}, max_length=300)),
                ('house_help_pan_number', models.CharField(max_length=300)),
                ('house_help_pan_doc', models.FileField(upload_to='files/')),
                ('house_help_contact', models.CharField(max_length=300)),
                ('house_help_aadhar_number', models.CharField(max_length=300)),
                ('house_help_aadhar_doc', models.FileField(upload_to='files/')),
                ('house_help_address', models.CharField(max_length=300)),
                ('house_help_city', models.CharField(max_length=300)),
                ('house_help_state', models.CharField(max_length=300)),
                ('house_help_pin', models.CharField(max_length=300)),
                ('other_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('other_document_specifications', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=300)),
                ('tenant_pan_number', models.CharField(max_length=300)),
                ('tenant_pan_doc', models.FileField(upload_to='files/')),
                ('tenant_contact', models.CharField(max_length=300)),
                ('tenant_aadhar_number', models.CharField(max_length=300)),
                ('tenant_aadhar_doc', models.FileField(upload_to='files/')),
                ('tenant_address', models.CharField(max_length=300)),
                ('tenant_city', models.CharField(max_length=300)),
                ('tenant_state', models.CharField(max_length=300)),
                ('tenant_pin_code', models.CharField(max_length=300)),
                ('tenant_email', models.CharField(max_length=300)),
                ('tenant_other_doc', models.FileField(blank=True, null=True, upload_to='files/')),
                ('tenant_doc_specification', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_from_date', models.DateField()),
                ('tenant_to_date', models.DateField(blank=True, null=True)),
                ('tenant_agreement', models.FileField(upload_to='tenant_agreements/')),
                ('tenant_noc', models.FileField(upload_to='tenant_nocs/')),
                ('aadhar_pan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhar_pan_allocations', to='SocietyApi.tenantmaster')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_allocations', to='SocietyApi.members')),
                ('tenant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_name_allocations', to='SocietyApi.tenantmaster')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_management_api_wing_flat', to='SocietyApi.wingflatunique')),
            ],
        ),
        migrations.CreateModel(
            name='HouseHelpAllocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=300)),
                ('house_help_period_from', models.DateField(blank=True, null=True)),
                ('house_help_period_to', models.DateField(blank=True, null=True)),
                ('aadhar_pan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aadhar_pan_allocations_new', to='SocietyApi.househelp')),
                ('house_help_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_allocations_new', to='SocietyApi.househelp')),
                ('member_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_allocations_new', to='SocietyApi.members')),
                ('wing_flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique')),
            ],
        ),
    ]
