# Generated by Django 3.2.12 on 2024-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0014_meetings_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantallocation',
            name='no_of_members',
            field=models.CharField(default=0, max_length=300),
        ),
    ]
