# Generated by Django 3.2.12 on 2024-02-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0018_alter_meetings_meeting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='files/')),
                ('attendance', models.CharField(max_length=200)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members')),
            ],
        ),
    ]
