# Generated by Django 3.2.12 on 2024-02-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0020_alter_attendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
