# Generated by Django 3.2.12 on 2024-02-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0021_auto_20240227_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='flat',
            new_name='flat_no',
        ),
    ]
