# Generated by Django 3.2.12 on 2024-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0022_rename_flat_attendance_flat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
