# Generated by Django 3.2.12 on 2024-02-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0023_alter_attendance_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='meeting_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.meetings'),
        ),
    ]
