# Generated by Django 3.2.12 on 2024-02-27 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0024_attendance_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.meetings'),
        ),
    ]
