# Generated by Django 3.2.12 on 2024-02-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0027_auto_20240227_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='flat_id',
        ),
    ]
