# Generated by Django 3.2.12 on 2024-02-28 05:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0028_remove_suggestion_flat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='minutes_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AddField(
            model_name='meetings',
            name='minutes_document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='meetings',
            name='minutes_otehr_doc',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
