# Generated by Django 3.2.12 on 2024-02-28 05:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0029_auto_20240228_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='minutes_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
