# Generated by Django 3.2.12 on 2024-03-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0031_alter_flatmembervehicle_unique_member_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societybank',
            name='society_creation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='SocietyApi.societycreation'),
        ),
    ]
