# Generated by Django 3.2.12 on 2024-03-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0033_alter_societybank_society_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flathomeloan',
            name='unique_member_shares',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='SocietyApi.members'),
        ),
    ]
