# Generated by Django 3.2.12 on 2024-03-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0037_flatdetail_date_of_cessation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatdetail',
            name='unique_member_shares',
        ),
    ]
