# Generated by Django 3.2.12 on 2024-03-02 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0038_remove_flatdetail_unique_member_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='SocietyApi.wingflatunique'),
        ),
    ]
