# Generated by Django 3.2.12 on 2024-03-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0039_alter_members_wing_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdetail',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='SocietyApi.wingflatunique'),
        ),
    ]
