# Generated by Django 3.2.12 on 2024-03-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0042_remove_flatdetail_date_of_cessation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_position',
            field=models.CharField(choices=[('nominal_member', 'Nominal Member'), ('comittee_member', 'Comittee Member'), ('member', 'Member')], default='member', max_length=200),
        ),
    ]
