# Generated by Django 3.2.12 on 2024-03-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0044_alter_members_member_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_position',
            field=models.CharField(choices=[('nominal_member', 'Nominal Member'), ('committe_member', 'Commitee Member'), ('member', 'Member')], max_length=200),
        ),
    ]
