# Generated by Django 3.2.12 on 2024-03-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0045_alter_members_member_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='flat_status',
        ),
    ]
