# Generated by Django 3.2.12 on 2024-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0047_alter_members_member_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flathomeloan',
            name='bank_loan_status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=200),
        ),
    ]
