# Generated by Django 3.2.12 on 2024-03-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0048_alter_flathomeloan_bank_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flathomeloan',
            name='bank_loan_status',
            field=models.CharField(choices=[('', 'Select Status'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=200),
        ),
    ]
