# Generated by Django 3.2.12 on 2024-03-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0051_alter_flatmembervehicle_chargable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmembervehicle',
            name='chargable',
            field=models.CharField(default='', max_length=200),
        ),
    ]
