# Generated by Django 3.2.12 on 2024-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0053_auto_20240308_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatmembervehicle',
            name='chargable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
