# Generated by Django 3.2.12 on 2024-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0055_rename_vehicle_chargable_flatmembervehicle_select_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=200)),
                ('nature', models.CharField(max_length=200)),
                ('gst_number', models.CharField(max_length=200)),
                ('alis', models.CharField(max_length=200)),
                ('based_on', models.CharField(max_length=200)),
                ('contact_person_name', models.CharField(max_length=200)),
                ('group_name', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person_number', models.CharField(max_length=200)),
                ('pan_number', models.CharField(max_length=200)),
                ('fixed', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person_email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=200)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=200)),
                ('bank_branch_name', models.CharField(max_length=200)),
                ('opening_balance', models.CharField(max_length=200)),
                ('dr_cr', models.CharField(max_length=200)),
            ],
        ),
    ]
