# Generated by Django 3.2.12 on 2024-03-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0056_assets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Ledger',
        ),
    ]
