# Generated by Django 3.2.12 on 2024-04-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0058_voucherindexing_vouchertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='bank_branch_name',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='ledger',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
