# Generated by Django 3.2.12 on 2024-04-07 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocietyApi', '0059_auto_20240403_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('bug', 'Bug'), ('add', 'Add Feature')], max_length=200)),
                ('test_description', models.TextField()),
                ('test_status', models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('in_progress', 'In Progress')], max_length=200)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
