# Generated by Django 3.2.12 on 2024-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0061_alter_unittest_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittest',
            name='test_status',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('in_progress', 'In Progress')], max_length=200, null=True),
        ),
    ]
