# Generated by Django 3.2.12 on 2024-04-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0062_alter_unittest_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittest',
            name='test_status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('pending', 'Pending'), ('in_progress', 'In Progress')], default='pending', max_length=200),
        ),
    ]
