# Generated by Django 3.2.12 on 2024-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0063_alter_unittest_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittest',
            name='review',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'closed')], default='open', max_length=200),
        ),
    ]
