# Generated by Django 3.2.12 on 2024-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0064_unittest_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittest',
            name='review',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=200),
        ),
    ]
