# Generated by Django 3.2.12 on 2024-04-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0065_alter_unittest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchertype',
            name='voucher_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vouchertype',
            name='voucher_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('general', 'General'), ('expenses', 'Expenses'), ('income', 'Income'), ('payment', 'Payment'), ('receipt', 'Receipt')], max_length=200),
        ),
    ]
