# Generated by Django 3.2.12 on 2024-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0066_auto_20240416_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertype',
            name='voucher_name',
            field=models.CharField(max_length=200),
        ),
    ]
