# Generated by Django 3.2.12 on 2024-04-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0067_alter_vouchertype_voucher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTypeCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('general', 'General'), ('expenses', 'Expenses'), ('income', 'Income'), ('payment', 'Payment'), ('receipt', 'Receipt')], max_length=200)),
                ('voucher_name', models.CharField(max_length=200)),
                ('voucher_short_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='voucherindexing',
            name='voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchertypecreation'),
        ),
        migrations.DeleteModel(
            name='VoucherType',
        ),
    ]
