# Generated by Django 3.2.12 on 2024-04-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0067_alter_vouchertype_voucher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='based_on',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
