# Generated by Django 3.2.12 on 2024-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0067_alter_vouchertype_voucher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertype',
            name='voucher_name',
            field=models.CharField(default='sale', max_length=200),
        ),
    ]
