# Generated by Django 3.2.12 on 2024-04-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0068_alter_ledger_based_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucherindexing',
            unique_together={('voucher_type', 'from_date', 'to_date')},
        ),
    ]
