# Generated by Django 3.2.12 on 2024-04-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0069_alter_voucherindexing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucherindexing',
            unique_together=set(),
        ),
    ]
