# Generated by Django 3.2.12 on 2024-04-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0071_voucherindexing_voucher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherindexing',
            name='voucher_number',
            field=models.CharField(max_length=250),
        ),
    ]
