# Generated by Django 3.2.12 on 2024-05-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0072_alter_voucherindexing_voucher_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseVoucherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('ledger_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.ledger')),
            ],
        ),
    ]
