# Generated by Django 3.2.12 on 2024-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0073_purchasevouchermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societycreation',
            name='gst_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='societycreation',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='societycreation',
            name='registration_number',
            field=models.CharField(max_length=100),
        ),
    ]
