# Generated by Django 3.2.12 on 2024-05-10 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0074_auto_20240510_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societycreation',
            name='gst_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='GST number must be exactly 15 digits', regex='^\\d{15}$')]),
        ),
        migrations.AlterField(
            model_name='societycreation',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='PAN number must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
    ]
