# Generated by Django 3.2.12 on 2024-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0077_auto_20240510_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societycreation',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
