# Generated by Django 3.2.12 on 2024-05-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0078_alter_societycreation_alternate_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societycreation',
            name='society_name',
            field=models.CharField(max_length=100),
        ),
    ]
