# Generated by Django 3.2.12 on 2024-05-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0079_alter_societycreation_society_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societycreation',
            name='pin_code',
            field=models.CharField(max_length=60),
        ),
    ]
