# Generated by Django 3.2.12 on 2024-05-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0081_wingflat_society_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wingflat',
            name='society_creation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.societycreation'),
        ),
    ]
