# Generated by Django 3.2.12 on 2024-05-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0083_alter_wingflat_society_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatshares',
            name='unique_member_shares',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members'),
        ),
        migrations.AlterField(
            model_name='flatshares',
            name='wing_flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique'),
        ),
    ]
