# Generated by Django 3.2.12 on 2024-05-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0084_auto_20240514_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatgst',
            name='unique_member_shares',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.members'),
        ),
        migrations.AlterField(
            model_name='flatgst',
            name='wing_flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique'),
        ),
        migrations.AlterField(
            model_name='flathomeloan',
            name='unique_member_shares',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='SocietyApi.members'),
        ),
        migrations.AlterField(
            model_name='flathomeloan',
            name='wing_flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique'),
        ),
    ]
