# Generated by Django 3.2.12 on 2024-05-17 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0085_auto_20240514_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='member_aadhar_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits', regex='^[a-zA-Z0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_pan_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='PAN number must be exactly 10 digits', regex='^[a-zA-Z0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='nominees',
            name='nominee_aadhar_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits', regex='^[a-zA-Z0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='nominees',
            name='nominee_pan_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='PAN number must be exactly 10 digits', regex='^[a-zA-Z0-9]{10}$')]),
        ),
    ]
