# Generated by Django 3.2.12 on 2024-05-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0086_auto_20240517_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatgst',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique'),
        ),
        migrations.AlterField(
            model_name='flathomeloan',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique'),
        ),
        migrations.AlterField(
            model_name='flatshares',
            name='wing_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.wingflatunique'),
        ),
    ]
