# Generated by Django 4.0 on 2024-06-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0011_auto_20240412_0908'),
        ('SocietyApi', '0088_auto_20240520_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareOnLedgerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_name', models.CharField(max_length=200)),
                ('shares_type', models.CharField(choices=[('pieces', 'Pieces'), ('unit', 'Unit')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherCreationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=100)),
                ('voucher_number', models.CharField(max_length=200)),
                ('booking_date', models.DateField()),
                ('amount_in_words', models.CharField(max_length=250)),
                ('narration', models.CharField(max_length=300)),
                ('cheque_number', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchertype')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedSharesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ledger_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedLedgersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amt', models.IntegerField(blank=True, null=True)),
                ('credit_amt', models.IntegerField(blank=True, null=True)),
                ('ledger_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.ledger')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchercreationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenterOnLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApp.costcenter')),
                ('related_ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.relatedledgersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AgainstRefrenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pending_amt', models.IntegerField()),
                ('final_amt', models.IntegerField()),
                ('allocated_amt', models.IntegerField()),
                ('voucher_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchercreationmodel')),
            ],
        ),
    ]
