# Generated by Django 4.0 on 2024-06-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0092_alter_costcenteronledger_related_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='againstrefrencemodel',
            name='date',
        ),
        migrations.AddField(
            model_name='againstrefrencemodel',
            name='voucher_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='againstrefrencemodel',
            name='voucher_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchercreationmodel'),
        ),
        migrations.AlterField(
            model_name='againstrefrencemodel',
            name='voucher_number',
            field=models.CharField(max_length=100),
        ),
    ]
