# Generated by Django 4.0 on 2024-06-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0094_alter_againstrefrencemodel_voucher_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='againstrefrencemodel',
            name='voucher_type',
        ),
        migrations.RemoveField(
            model_name='costcenteronledger',
            name='related_ledger',
        ),
        migrations.AddField(
            model_name='againstrefrencemodel',
            name='against_related_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.relatedledgersmodel'),
        ),
        migrations.AddField(
            model_name='costcenteronledger',
            name='cost_center_related_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.relatedledgersmodel'),
        ),
        migrations.AddField(
            model_name='costcenteronledger',
            name='cost_center_related_shares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.relatedsharesmodel'),
        ),
        migrations.AddField(
            model_name='relatedsharesmodel',
            name='voucher_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchercreationmodel'),
        ),
    ]
