# Generated by Django 4.0 on 2024-06-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0095_remove_againstrefrencemodel_voucher_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='againstrefrencemodel',
            name='against_related_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.relatedledgersmodel'),
        ),
        migrations.AlterField(
            model_name='relatedsharesmodel',
            name='voucher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchercreationmodel'),
        ),
    ]
