# Generated by Django 4.0 on 2024-06-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0096_alter_againstrefrencemodel_against_related_ledger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costcenteronledger',
            old_name='cost_center_related_ledger',
            new_name='related_ledger',
        ),
        migrations.RemoveField(
            model_name='costcenteronledger',
            name='cost_center_related_shares',
        ),
        migrations.AddField(
            model_name='relatedledgersmodel',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatedledgersmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatedledgersmodel',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatedledgersmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
