# Generated by Django 4.0 on 2024-06-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0097_rename_cost_center_related_ledger_costcenteronledger_related_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('particulars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.ledger')),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchertype')),
            ],
        ),
    ]
