# Generated by Django 4.0 on 2024-07-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0099_auto_20240625_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='actual_running_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
