# Generated by Django 4.0 on 2024-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0100_generalledger_actual_running_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledger',
            name='actual_running_amount',
        ),
        migrations.AddField(
            model_name='generalledger',
            name='actual_running_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
