# Generated by Django 4.0 on 2024-07-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0101_remove_generalledger_actual_running_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledger',
            name='actual_running_amt',
        ),
    ]
