# Generated by Django 4.0 on 2024-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0102_remove_generalledger_actual_running_amt'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('contact', models.CharField(max_length=400)),
                ('website', models.CharField(max_length=400)),
                ('address', models.CharField(default='Neque porro quisquam est qui dolorem ipsum quia dolor sit 403 sit.', max_length=400)),
            ],
        ),
    ]
