# Generated by Django 4.0 on 2024-07-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0103_vistingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistingcard',
            name='name',
            field=models.CharField(default='Alan', max_length=400),
        ),
    ]
