# Generated by Django 5.0.7 on 2024-07-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0105_alter_vistingcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='againstrefrencemodel',
            name='against_related_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.ledger'),
        ),
    ]
