# Generated by Django 5.0.7 on 2024-07-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0106_alter_againstrefrencemodel_against_related_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='againstrefrencemodel',
            name='allocated_amt',
        ),
    ]
