# Generated by Django 5.0.7 on 2024-07-15 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0107_remove_againstrefrencemodel_allocated_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercreationmodel',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vouchercreationmodel',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.ledger'),
        ),
        migrations.CreateModel(
            name='RelatedStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchases_total', models.IntegerField(blank=True, null=True)),
                ('sales_total', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.vouchercreationmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='RelatedSharesModel',
        ),
    ]
