# Generated by Django 5.0.7 on 2024-07-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0108_vouchercreationmodel_vendor_invoice_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareOnLedgerModel',
            new_name='StockOnLedgerModel',
        ),
        migrations.RenameField(
            model_name='stockonledgermodel',
            old_name='shares_name',
            new_name='stock_name',
        ),
        migrations.RenameField(
            model_name='stockonledgermodel',
            old_name='shares_type',
            new_name='stock_type',
        ),
        migrations.RemoveField(
            model_name='relatedstockmodel',
            name='purchases_total',
        ),
        migrations.RemoveField(
            model_name='relatedstockmodel',
            name='sales_total',
        ),
        migrations.AddField(
            model_name='relatedstockmodel',
            name='stock_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.stockonledgermodel'),
        ),
    ]
