# Generated by Django 5.0.7 on 2024-07-15 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0109_rename_shareonledgermodel_stockonledgermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedstockmodel',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocietyApi.stockonledgermodel'),
        ),
    ]
