# Generated by Django 5.0.7 on 2024-07-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0110_alter_relatedstockmodel_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercreationmodel',
            name='total_purchases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
