# Generated by Django 5.0.7 on 2024-07-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0111_vouchercreationmodel_total_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
