# Generated by Django 5.0.7 on 2024-07-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0113_alter_generalledger_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercreationmodel',
            name='credit_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vouchercreationmodel',
            name='debit_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
