# Generated by Django 5.0.7 on 2024-07-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0117_againstrefrencemodel_voucher_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='againstrefrencemodel',
            name='allocated_amt',
            field=models.IntegerField(null=True),
        ),
    ]
