# Generated by Django 5.0.7 on 2024-07-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0119_vouchercreationmodel_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercreationmodel',
            name='prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vouchercreationmodel',
            name='suffix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
