# Generated by Django 5.0.7 on 2024-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0120_alter_vouchercreationmodel_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='allow_against_refrence',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'YES')], default='NO', max_length=200),
        ),
    ]
