# Generated by Django 5.0.7 on 2024-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0121_ledger_allow_against_refrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='allow_against_refrence',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=200),
        ),
    ]
