# Generated by Django 5.0.6 on 2024-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0123_vouchercreationmodel_cheque_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercreationmodel',
            name='counter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voucherindexing',
            name='counter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
