# Generated by Django 5.0.6 on 2024-08-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApi', '0126_societymaintainancebill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='dr_cr',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Cr', 'Dr')], max_length=200),
        ),
    ]
