# Generated by Django 3.2.12 on 2024-03-18 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Childs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='SocietyApp.childs')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(choices=[('fixed_assets', 'Fixed Assets'), ('investment', 'Investment'), ('misc_assets', 'Misc Assets')], max_length=100)),
                ('childs', models.ManyToManyField(to='SocietyApp.Childs')),
            ],
        ),
    ]
