# Generated by Django 3.2.12 on 2024-03-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0002_auto_20240321_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='SocietyApp.childs'),
        ),
    ]
