# Generated by Django 3.2.12 on 2024-03-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0004_costcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_center', to='SocietyApp.costcenter'),
        ),
    ]
