# Generated by Django 3.2.12 on 2024-03-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0005_alter_costcenter_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childs',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='childs',
            unique_together={('name', 'parent')},
        ),
    ]
