# Generated by Django 3.2.12 on 2024-04-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0006_auto_20240330_0507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
