# Generated by Django 3.2.12 on 2024-04-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0009_alter_costcenter_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childs',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='childs',
            unique_together=set(),
        ),
    ]
