# Generated by Django 3.2.12 on 2024-04-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0010_auto_20240412_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('name', 'parent')},
        ),
    ]
