# Generated by Django 4.0 on 2024-07-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0011_auto_20240412_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300)),
                ('contact', models.CharField(max_length=400)),
                ('website', models.CharField(max_length=400)),
            ],
        ),
    ]
