# Generated by Django 4.0 on 2024-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0012_vistingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistingcard',
            name='address',
            field=models.CharField(default='Neque porro quisquam est qui dolorem ipsum quia dolor sit 403 sit.', max_length=400),
        ),
    ]
