# Generated by Django 4.0 on 2024-07-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocietyApp', '0013_vistingcard_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VistingCard',
        ),
    ]
